services:
  db:
    image: postgres
    container_name: postgres_container
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "8022:5432"

  redis:
    image: redis
    container_name: redis_container
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - redis_data:/data
    ports:
      - "8023:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_server_container
    ports:
      - "8020:8080"
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - /srv/file-storage:/app/file-storage

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_server_container
    ports:
      - "8021:80"
    restart: unless-stopped

volumes:
    db_data:
    redis_data: