services:
  postgres:
    image: postgres
    container_name: postgres_container
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "8022:5432"

  redis:
    image: redis
    container_name: redis_container
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - redis_data:/data
    ports:
      - "8023:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_server_container
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - postgres
      - redis
    volumes:
      - /srv/file-storage:/app/file-storage
    ports:
      - "8020:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_server_container
    restart: unless-stopped
    ports:
      - "8021:80"

volumes:
    db_data:
    redis_data: