services:
  db:
    image: postgres
    container_name: postgres_container
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "8022:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_server_container
    ports:
      - "8020:8080"
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_server_container
    ports:
      - "8021:80"
    restart: unless-stopped

volumes:
    db_data: