logging:
  level:
    root: INFO

spring:
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  session:
    redis:
      namespace: zorphy

server:
  servlet:
    session:
      timeout: 12h
    context-path: /api