logging:
  level:
    root: INFO

spring:
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://db:5432/${POSTGRES_DB}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update