spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
  data:
    redis:
      host: redis
      port: 6379

app:
  base-url: https://server.zorphy.net/api/

file-storage:
  directory: /app/file-storage
  compression-rate: 20