name: Deploy to rpi5

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4

    - name: Create .env file from secret
      run: |
        echo "${{secrets.ENV_FILE}}" > .env

    - name: Build and run Docker containers with compose
      run: |
        docker compose build
        docker compose up -d --no-deps backend frontend