name: Deploy to rpi5

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4

    - name: Build and run Docker containers with compose
      run: |
        docker compose down
        docker compose build
        docker compose up -d