name: Deploy to rpi5

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build and run the Docker image for the backend
      run: |
        docker build ./backend --file ./backend/Dockerfile --tag backend_server_image:latest
        docker stop backend_server_container || true
        docker rm backend_server_container || true
        docker run -d -p 8020:8080 --name backend_server_container --restart unless-stopped backend_server_image:latest

    - name: Build and run the Docker image for the frontend
      run: |
        docker build ./frontend --file ./frontend/Dockerfile --tag frontend_server_image:latest
        docker stop frontend_server_container || true
        docker rm frontend_server_container || true
        docker run -d -p 8021:80 --name frontend_server_container --restart unless-stopped frontend_server_image:latest
