name: Deploy to rpi5

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4

    - name: Create .env file from secret
      run: |
        echo "${{secrets.ENV_FILE}}" > .env

    - name: Build containers with docker compose
      run: docker compose build

    - name: Run docker containers
      run: docker compose up -d backend frontend

    - name: Clean up dangling docker images
      run: docker image prune -f